package com.alx.scraper.repository;

import com.alx.scraper.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * Repository interface for {@link User} entities.
 * Extends {@link JpaRepository} to provide standard CRUD operations
 * and pagination/sorting capabilities for User objects.
 *
 * ALX Focus: Demonstrates Spring Data JPA's power to automatically generate
 * repository implementations, reducing boilerplate code for data access.
 * The `findByUsername` method is a custom query generated by method name convention.
 */
@Repository
public interface UserRepository extends JpaRepository<User, Long> {

    /**
     * Finds a user by their username.
     * This method leverages Spring Data JPA's query derivation from method names.
     *
     * @param username The username to search for.
     * @return An {@link Optional} containing the found user, or empty if not found.
     */
    Optional<User> findByUsername(String username);

    /**
     * Checks if a user with the given username exists.
     *
     * @param username The username to check.
     * @return True if a user with the username exists, false otherwise.
     */
    boolean existsByUsername(String username);
}