"""initial migration

Revision ID: 20231027120000
Revises:
Create Date: 2023-10-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20231027120000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_types_id'), 'metric_types', ['id'], unique=False)
    op.create_index(op.f('ix_metric_types_name'), 'metric_types', ['name'], unique=True)

    op.create_table('services',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    op.create_table('alert_rules',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('metric_type_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_types.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_alert_rules_metric_type_id'), 'alert_rules', ['metric_type_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_service_id'), 'alert_rules', ['service_id'], unique=False)

    op.create_table('metric_records',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('metric_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_types.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_records_id'), 'metric_records', ['id'], unique=False)
    op.create_index(op.f('ix_metric_records_metric_type_id'), 'metric_records', ['metric_type_id'], unique=False)
    op.create_index(op.f('ix_metric_records_service_id'), 'metric_records', ['service_id'], unique=False)
    op.create_index(op.f('ix_metric_records_timestamp'), 'metric_records', ['timestamp'], unique=False)

    op.create_table('alert_notifications',
    sa.Column('alert_rule_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('metric_type_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_value', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_types.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_notifications_alert_rule_id'), 'alert_notifications', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_alert_notifications_id'), 'alert_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_alert_notifications_metric_type_id'), 'alert_notifications', ['metric_type_id'], unique=False)
    op.create_index(op.f('ix_alert_notifications_service_id'), 'alert_notifications', ['service_id'], unique=False)
    op.create_index(op.f('ix_alert_notifications_triggered_at'), 'alert_notifications', ['triggered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_notifications_triggered_at'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_service_id'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_metric_type_id'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_id'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_alert_rule_id'), table_name='alert_notifications')
    op.drop_table('alert_notifications')
    op.drop_index(op.f('ix_metric_records_timestamp'), table_name='metric_records')
    op.drop_index(op.f('ix_metric_records_service_id'), table_name='metric_records')
    op.drop_index(op.f('ix_metric_records_metric_type_id'), table_name='metric_records')
    op.drop_index(op.f('ix_metric_records_id'), table_name='metric_records')
    op.drop_table('metric_records')
    op.drop_index(op.f('ix_alert_rules_service_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_metric_type_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_metric_types_name'), table_name='metric_types')
    op.drop_index(op.f('ix_metric_types_id'), table_name='metric_types')
    op.drop_table('metric_types')
    # ### end Alembic commands ###

```

#### `scripts/seed_data.py`
```python