from locust import HttpUser, task, between
import random

class CMSUser(HttpUser):
    wait_time = between(1, 3) # Users wait between 1 and 3 seconds between tasks
    host = "http://localhost:5000" # Default host, can be overridden with -H

    # Store tokens for authenticated requests
    auth_tokens = {}
    users_data = [] # To store user credentials for login

    def on_start(self):
        """On start of user, register, login, and get an access token."""
        self.register_and_login()
        self.get_categories() # Populate categories for other tasks
        self.get_tags() # Populate tags for other tasks

    def register_and_login(self):
        # Only register new user if we haven't reached a certain count
        if len(CMSUser.users_data) < 100: # Limit number of registered users
            username = f"testuser_{random.randint(10000, 999999)}"
            email = f"{username}@example.com"
            password = "password123"

            register_payload = {
                "username": username,
                "email": email,
                "password": password
            }
            register_res = self.client.post("/api/v1/register", json=register_payload, catch_response=True)
            if register_res.status_code == 201:
                print(f"Registered user: {username}")
                CMSUser.users_data.append({"email": email, "password": password})
            elif register_res.status_code == 400 and "already exists" in register_res.text:
                print(f"User {username} already exists (might be from previous run). Trying to log in instead.")
                CMSUser.users_data.append({"email": email, "password": password}) # Add to list to try login

        # Always try to login, using existing users or the newly registered one
        if CMSUser.users_data:
            user_creds = random.choice(CMSUser.users_data)
            login_payload = {
                "email": user_creds["email"],
                "password": user_creds["password"]
            }
            login_res = self.client.post("/api/v1/login", json=login_payload, name="/api/v1/login", catch_response=True)
            if login_res.status_code == 200:
                self.auth_tokens = login_res.json()
                print(f"Logged in as {user_creds['email']}")
                login_res.success()
            else:
                login_res.failure(f"Failed to log in: {login_res.text}")
                self.auth_tokens = {} # Clear tokens if login fails
        else:
            print("No users available to log in.")


    def get_auth_headers(self):
        if not self.auth_tokens:
            self.register_and_login() # Try to get tokens if not available
        if self.auth_tokens:
            return {"Authorization": f"Bearer {self.auth_tokens['access_token']}"}
        return {}

    def get_categories(self):
        res = self.client.get("/api/v1/categories", name="/api/v1/categories [cache-hit]", catch_response=True)
        if res.status_code == 200:
            self.categories = res.json()
        else:
            res.failure("Failed to fetch categories")

    def get_tags(self):
        res = self.client.get("/api/v1/tags", name="/api/v1/tags [cache-hit]", catch_response=True)
        if res.status_code == 200:
            self.tags = res.json()
        else:
            res.failure("Failed to fetch tags")

    @task(5) # 5 times more likely than unauthenticated tasks
    def get_content_authenticated(self):
        headers = self.get_auth_headers()
        if headers:
            self.client.get("/api/v1/content", headers=headers, name="/api/v1/content [authenticated] [cache-hit]")

    @task(3)
    def create_content(self):
        headers = self.get_auth_headers()
        if not headers or not self.categories or not self.tags:
            return # Skip if not authenticated or no categories/tags

        title = f"Performance Test Article {random.randint(1, 1000000)}"
        body = f"This is a test article content generated by Locust user {self.environment.runner.user_count}."
        
        category_id = random.choice(self.categories)['id'] if self.categories else None
        random_tags = random.sample(self.tags, min(len(self.tags), random.randint(1,3)))
        tag_ids = [tag['id'] for tag in random_tags] if random_tags else []

        payload = {
            "title": title,
            "body": body,
            "user_id": 1, # Assuming author ID 1 exists, or dynamically fetch
            "category_id": category_id,
            "tag_ids": tag_ids,
            "status": random.choice(["draft", "published"]) # Try to publish
        }

        self.client.post("/api/v1/content", json=payload, headers=headers)

    @task(2)
    def get_specific_content(self):
        headers = self.get_auth_headers()
        if headers:
            # First, list content to get an ID
            list_res = self.client.get("/api/v1/content?status=published&per_page=1", headers=headers, name="/api/v1/content [list for ID]")
            if list_res.status_code == 200 and list_res.json() and list_res.json()['items']:
                content_id = random.choice(list_res.json()['items'])['id']
                self.client.get(f"/api/v1/content/{content_id}", headers=headers, name="/api/v1/content/{id} [authenticated] [cache-hit]")
            else:
                list_res.failure("Could not get content ID for specific content test.")

    @task(1) # Less frequent task
    def update_content(self):
        headers = self.get_auth_headers()
        if not headers:
            return

        # List content to get an ID that the user might have permission to update
        # For simplicity, we'll try to update any content from the list, might result in 403 for non-admins
        list_res = self.client.get("/api/v1/content?status=draft&per_page=1", headers=headers, name="/api/v1/content [list drafts for update]")
        if list_res.status_code == 200 and list_res.json() and list_res.json()['items']:
            content_id = random.choice(list_res.json()['items'])['id']
            update_payload = {
                "title": f"Updated Article {random.randint(1, 100000)}",
                "body": "This content has been updated by a performance test.",
                "status": random.choice(["draft", "published"])
            }
            self.client.put(f"/api/v1/content/{content_id}", json=update_payload, headers=headers)
        else:
            list_res.failure("Could not get draft content ID for update test.")


    # Unauthenticated tasks
    @task(5)
    def get_public_content(self):
        self.client.get("/api/v1/content?status=published", name="/api/v1/content [public] [cache-hit]")

    @task(2)
    def get_public_categories(self):
        self.client.get("/api/v1/categories", name="/api/v1/categories [public] [cache-hit]")

    @task(2)
    def get_public_tags(self):
        self.client.get("/api/v1/tags", name="/api/v1/tags [public] [cache-hit]")

    @task(1)
    def get_api_docs(self):
        self.client.get("/apidocs", name="/apidocs [static]")
```