const axios = require('axios');
const config = require('../config');
const logger = require('../utils/logger');

// This service acts as an abstraction layer for integrating with external payment gateways.
// In a real application, you'd integrate with specific providers (e.g., Stripe, Paystack, Flutterwave).
// For this example, we'll use a mock gateway.

class PaymentGatewayService {
  constructor() {
    this.api = axios.create({
      baseURL: config.paymentGateway.baseUrl,
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${config.paymentGateway.apiKey}`,
        'X-Secret-Key': config.paymentGateway.secret, // Example for additional auth
      },
      timeout: 10000, // 10 seconds timeout
    });
  }

  /**
   * Initiates a payment with the external gateway.
   * This typically involves tokenizing card details on the frontend and sending the token here.
   * For this mock, we simulate direct card/bank account payment.
   *
   * @param {object} paymentDetails - Details for the payment.
   *   e.g., { amount, currency, customerEmail, description, paymentMethodId/token }
   * @returns {Promise<object>} - Gateway's response, including status and transaction ID.
   */
  async initiatePayment(paymentDetails) {
    logger.info('Initiating payment with mock gateway:', paymentDetails);
    try {
      // Simulate API call to an external payment gateway
      const response = await this.api.post('/charge', {
        ...paymentDetails,
        // In a real scenario, sensitive data like full card details
        // would NOT be sent from your backend. Instead, a token
        // generated by the payment gateway's SDK on the frontend would be used.
        // For our mock, we can send a "paymentMethodId" or similar.
      });
      logger.info('Mock gateway payment response:', response.data);
      return response.data; // { status: 'success'|'failed', gatewayTransactionId: '...', message: '...' }
    } catch (error) {
      logger.error('Error initiating payment with mock gateway:', error.message, error.response?.data);
      throw new Error(`Payment gateway error: ${error.response?.data?.message || error.message}`);
    }
  }

  /**
   * Verifies the status of a transaction with the external gateway.
   * Important for handling asynchronous payment notifications (webhooks) or polling.
   *
   * @param {string} gatewayTransactionId - The transaction ID returned by the payment gateway.
   * @returns {Promise<object>} - Gateway's transaction status.
   */
  async verifyTransaction(gatewayTransactionId) {
    logger.info(`Verifying transaction ${gatewayTransactionId} with mock gateway.`);
    try {
      const response = await this.api.get(`/transactions/${gatewayTransactionId}/status`);
      logger.info('Mock gateway verification response:', response.data);
      return response.data; // { status: 'success'|'pending'|'failed', amount: ..., currency: ... }
    } catch (error) {
      logger.error(`Error verifying transaction ${gatewayTransactionId} with mock gateway:`, error.message, error.response?.data);
      throw new Error(`Transaction verification failed: ${error.response?.data?.message || error.message}`);
    }
  }

  /**
   * Processes a refund for a successful transaction.
   * @param {string} gatewayTransactionId - The original transaction ID from the gateway.
   * @param {number} amount - The amount to refund (can be partial).
   * @returns {Promise<object>} - Gateway's refund response.
   */
  async processRefund(gatewayTransactionId, amount) {
    logger.info(`Processing refund for transaction ${gatewayTransactionId} with mock gateway.`);
    try {
      const response = await this.api.post(`/refund`, {
        gatewayTransactionId,
        amount,
      });
      logger.info('Mock gateway refund response:', response.data);
      return response.data;
    } catch (error) {
      logger.error(`Error processing refund for ${gatewayTransactionId}:`, error.message, error.response?.data);
      throw new Error(`Refund failed: ${error.response?.data?.message || error.message}`);
    }
  }

  // --- Mock Payment Gateway Backend (for local testing without a real gateway) ---
  // In a real application, this would be a separate microservice or a real external API.
  // For simplicity, we'll embed a basic mock here for demonstration.
  // You would ideally replace this entire section with actual API calls to Stripe, Paystack etc.

  static async mockCharge(paymentDetails) {
    return new Promise(resolve => {
      setTimeout(() => {
        const transactionId = `MOCK-${Date.now()}-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
        const isSuccess = Math.random() < config.paymentGateway.mockSuccessRate;

        if (isSuccess) {
          logger.info(`MOCK Gateway: Payment ${transactionId} successful for ${paymentDetails.amount} ${paymentDetails.currency}`);
          resolve({
            status: 'success',
            gatewayTransactionId: transactionId,
            message: 'Payment successful',
            amount: paymentDetails.amount,
            currency: paymentDetails.currency,
          });
        } else {
          logger.warn(`MOCK Gateway: Payment ${transactionId} failed for ${paymentDetails.amount} ${paymentDetails.currency}`);
          resolve({
            status: 'failed',
            gatewayTransactionId: transactionId,
            message: 'Payment failed due to simulated error',
            amount: paymentDetails.amount,
            currency: paymentDetails.currency,
          });
        }
      }, config.paymentGateway.mockProcessingTime);
    });
  }

  static async mockVerify(gatewayTransactionId) {
    return new Promise(resolve => {
      setTimeout(() => {
        // Simulate a fixed successful status for verification
        logger.info(`MOCK Gateway: Verification for ${gatewayTransactionId} successful.`);
        resolve({
          status: 'success', // Or 'pending' or 'failed' based on previous mockCharge outcome
          gatewayTransactionId: gatewayTransactionId,
          amount: 1000, // This should be retrieved from a mock DB
          currency: 'NGN', // This should be retrieved from a mock DB
          message: 'Transaction verified',
        });
      }, config.paymentGateway.mockProcessingTime / 2); // Faster verification
    });
  }

  static async mockRefund(gatewayTransactionId, amount) {
    return new Promise(resolve => {
      setTimeout(() => {
        const refundId = `REFUND-${Date.now()}-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
        logger.info(`MOCK Gateway: Refund ${refundId} successful for transaction ${gatewayTransactionId}, amount ${amount}`);
        resolve({
          status: 'success',
          refundId: refundId,
          message: 'Refund successful',
        });
      }, config.paymentGateway.mockProcessingTime);
    });
  }
}

// If you were running a separate mock gateway server, you would export `PaymentGatewayService`
// and configure `config.paymentGateway.baseUrl` to point to it.
// For now, let's export the `mockCharge` methods if we are using it directly.
// In a real system, `this.api` methods would directly call the external API.

module.exports = new PaymentGatewayService(); // Export an instance

// For the embedded mock gateway server concept (if you wanted to run it as part of this app for testing)
// We are skipping creating a full mock server, instead `initiatePayment` directly calls a mock static method.
// You can adjust `initiatePayment` to use `PaymentGatewayService.mockCharge` directly if no separate mock server.
// const paymentGatewayService = new PaymentGatewayService();
// paymentGatewayService.initiatePayment = PaymentGatewayService.mockCharge;
// paymentGatewayService.verifyTransaction = PaymentGatewayService.mockVerify;
// paymentGatewayService.processRefund = PaymentGatewayService.mockRefund;
// module.exports = paymentGatewayService;
```
*Note*: The `PaymentGatewayService` above currently shows an `axios` setup to an *external* mock. For simplicity in demonstrating *this* project, the `initiatePayment` method in `transactionService.js` below will directly call the static `mockCharge` method. In a real integration, the `axios` calls would be to the actual gateway APIs.

#### `src/services/transactionService.js`

```javascript