```ini
[alembic]
# path to migration scripts
script_location = alembic
# template environment
file_template = %%(rev)s_%%(head)s
# timezone for timestamps in migration files
timezone = UTC
# where to store environment files
version_locations = %(script_location)s/versions
# script.py.mako is the default, but you can specify a custom one
# template_path =

# A base module for the --autogenerate option to load,
# for example, 'myapp.models'. This can also be a comma
# separated list.  When multiple modules are present,
# the models are unioned.
# autogenerate_targets = app.db.models
# When you have multiple metadata objects, you can specify them like this:
# autogenerate_targets = project_name.module.model_name:metadata_var

# If you use the -autogenerate option, please make sure the metadata for the
# database models that Alembic manages is available in the env.py file.
# target_metadata must be set in env.py

# logging configuration
[loggers]
keys = root,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
formatter = generic
args = (sys.stderr,)

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
```