```javascript
const httpStatus = require('http-status');
const { Category } = require('../models');
const ApiError = require('../utils/ApiError');
const logger = require('../utils/logger');
const { Op } = require('sequelize');

/**
 * Create a category
 * @param {Object} categoryBody
 * @returns {Promise<Category>}
 */
const createCategory = async (categoryBody) => {
  if (categoryBody.slug && (await Category.isSlugTaken(categoryBody.slug))) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'Slug already taken');
  }
  // If slug is not provided, it will be generated by the model hook.
  // We still need to check for uniqueness after the hook.
  if (!categoryBody.slug) {
    const tempCategory = Category.build(categoryBody);
    await tempCategory.validate(); // Triggers beforeValidate hook
    if (await Category.isSlugTaken(tempCategory.slug)) {
      throw new ApiError(httpStatus.CONFLICT, `Generated slug '${tempCategory.slug}' is already taken. Please provide a unique slug.`);
    }
  }

  return Category.create(categoryBody);
};

/**
 * Query for categories
 * @param {Object} filter - Sequelize filter
 * @param {Object} options - Query options like sortBy, limit, page
 * @returns {Promise<QueryResult>}
 */
const queryCategories = async (filter, options) => {
  const { sortBy, limit, page } = options;
  const offset = (page - 1) * limit;

  let order = [];
  if (sortBy) {
    const [field, sortOrder] = sortBy.split(':');
    order.push([field, sortOrder.toUpperCase()]);
  } else {
    order.push(['createdAt', 'DESC']); // Default sort
  }

  const where = {};
  if (filter.name) {
    where.name = { [Op.iLike]: `%${filter.name}%` };
  }
  if (filter.slug) {
    where.slug = filter.slug; // Exact match for slug
  }

  const { count, rows: categories } = await Category.findAndCountAll({
    where,
    order,
    limit,
    offset,
  });

  return {
    categories,
    totalResults: count,
    limit,
    page,
    totalPages: Math.ceil(count / limit),
  };
};

/**
 * Get category by ID
 * @param {string} id
 * @returns {Promise<Category>}
 */
const getCategoryById = async (id) => {
  return Category.findByPk(id);
};

/**
 * Update category by ID
 * @param {string} categoryId
 * @param {Object} updateBody
 * @returns {Promise<Category>}
 */
const updateCategoryById = async (categoryId, updateBody) => {
  const category = await getCategoryById(categoryId);
  if (!category) {
    throw new ApiError(httpStatus.NOT_FOUND, 'Category not found');
  }
  if (updateBody.slug && updateBody.slug !== category.slug && (await Category.isSlugTaken(updateBody.slug))) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'Slug already taken');
  }
  Object.assign(category, updateBody);
  await category.save();
  return category;
};

/**
 * Delete category by ID
 * @param {string} categoryId
 * @returns {Promise<Category>}
 */
const deleteCategoryById = async (categoryId) => {
  const category = await getCategoryById(categoryId);
  if (!category) {
    throw new ApiError(httpStatus.NOT_FOUND, 'Category not found');
  }
  await category.destroy();
  return category;
};

// Add static method to Category model for checking existence
Category.isSlugTaken = async function (slug, excludeCategoryId) {
  const category = await this.findOne({ where: { slug } });
  return !!category && (excludeCategoryId ? category.id !== excludeCategoryId : true);
};

module.exports = {
  createCategory,
  queryCategories,
  getCategoryById,
  updateCategoryById,
  deleteCategoryById,
};
```