package com.ml_utilities_system.service;

import com.ml_utilities_system.dto.DatasetDTO;
import com.ml_utilities_system.exception.ResourceNotFoundException;
import com.ml_utilities_system.exception.ValidationException;
import com.ml_utilities_system.model.Dataset;
import com.ml_utilities_system.repository.DatasetRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.cache.annotation.Caching;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class DatasetService {

    @Autowired
    private DatasetRepository datasetRepository;

    @Transactional(readOnly = true)
    @Cacheable(value = "datasets", key = "#id")
    public DatasetDTO getDatasetById(Long id) {
        Dataset dataset = datasetRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Dataset not found with id: " + id));
        return convertToDTO(dataset);
    }

    @Transactional(readOnly = true)
    @Cacheable(value = "datasets", key = "'all' + #pageable.pageNumber + '_' + #pageable.pageSize")
    public Page<DatasetDTO> getAllDatasets(Pageable pageable) {
        return datasetRepository.findAll(pageable).map(this::convertToDTO);
    }

    @Transactional
    @Caching(evict = {
            @CacheEvict(value = "datasets", allEntries = true)
    })
    public DatasetDTO createDataset(DatasetDTO datasetDTO) {
        if (datasetRepository.existsByName(datasetDTO.getName())) {
            throw new ValidationException("Dataset with name '" + datasetDTO.getName() + "' already exists.");
        }
        Dataset dataset = convertToEntity(datasetDTO);
        dataset.setId(null); // Ensure ID is generated by DB
        return convertToDTO(datasetRepository.save(dataset));
    }

    @Transactional
    @Caching(evict = {
            @CacheEvict(value = "datasets", key = "#id"),
            @CacheEvict(value = "datasets", allEntries = true)
    })
    public DatasetDTO updateDataset(Long id, DatasetDTO datasetDTO) {
        Dataset existingDataset = datasetRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Dataset not found with id: " + id));

        // Check for name uniqueness if name is changed
        if (!existingDataset.getName().equals(datasetDTO.getName()) && datasetRepository.existsByName(datasetDTO.getName())) {
            throw new ValidationException("Dataset with name '" + datasetDTO.getName() + "' already exists.");
        }

        existingDataset.setName(datasetDTO.getName());
        existingDataset.setDescription(datasetDTO.getDescription());
        existingDataset.setFilePath(datasetDTO.getFilePath());
        existingDataset.setSizeBytes(datasetDTO.getSizeBytes());
        existingDataset.setFormat(datasetDTO.getFormat());
        // uploadedAt should not be updated

        return convertToDTO(datasetRepository.save(existingDataset));
    }

    @Transactional
    @Caching(evict = {
            @CacheEvict(value = "datasets", key = "#id"),
            @CacheEvict(value = "datasets", allEntries = true)
    })
    public void deleteDataset(Long id) {
        if (!datasetRepository.existsById(id)) {
            throw new ResourceNotFoundException("Dataset not found with id: " + id);
        }
        datasetRepository.deleteById(id);
    }

    private DatasetDTO convertToDTO(Dataset dataset) {
        if (dataset == null) return null;
        return new DatasetDTO(
                dataset.getId(),
                dataset.getName(),
                dataset.getDescription(),
                dataset.getFilePath(),
                dataset.getSizeBytes(),
                dataset.getFormat(),
                dataset.getUploadedAt(),
                dataset.getLastModifiedAt()
        );
    }

    private Dataset convertToEntity(DatasetDTO datasetDTO) {
        if (datasetDTO == null) return null;
        Dataset dataset = new Dataset();
        dataset.setId(datasetDTO.getId());
        dataset.setName(datasetDTO.getName());
        dataset.setDescription(datasetDTO.getDescription());
        dataset.setFilePath(datasetDTO.getFilePath());
        dataset.setSizeBytes(datasetDTO.getSizeBytes());
        dataset.setFormat(datasetDTO.getFormat());
        dataset.setUploadedAt(datasetDTO.getUploadedAt());
        dataset.setLastModifiedAt(datasetDTO.getLastModifiedAt());
        return dataset;
    }
}