package com.ml_utilities_system.service;

import com.ml_utilities_system.dto.FeatureDTO;
import com.ml_utilities_system.exception.ResourceNotFoundException;
import com.ml_utilities_system.exception.ValidationException;
import com.ml_utilities_system.model.Feature;
import com.ml_utilities_system.repository.FeatureRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.cache.annotation.Caching;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class FeatureService {

    @Autowired
    private FeatureRepository featureRepository;

    @Transactional(readOnly = true)
    @Cacheable(value = "features", key = "#id")
    public FeatureDTO getFeatureById(Long id) {
        Feature feature = featureRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Feature not found with id: " + id));
        return convertToDTO(feature);
    }

    @Transactional(readOnly = true)
    @Cacheable(value = "features", key = "'all' + #pageable.pageNumber + '_' + #pageable.pageSize")
    public Page<FeatureDTO> getAllFeatures(Pageable pageable) {
        return featureRepository.findAll(pageable).map(this::convertToDTO);
    }

    @Transactional
    @Caching(evict = {
            @CacheEvict(value = "features", allEntries = true)
    })
    public FeatureDTO createFeature(FeatureDTO featureDTO) {
        if (featureRepository.existsByNameAndVersion(featureDTO.getName(), featureDTO.getVersion())) {
            throw new ValidationException(String.format("Feature with name '%s' and version '%d' already exists.",
                    featureDTO.getName(), featureDTO.getVersion()));
        }
        Feature feature = convertToEntity(featureDTO);
        feature.setId(null); // Ensure ID is generated by DB
        return convertToDTO(featureRepository.save(feature));
    }

    @Transactional
    @Caching(evict = {
            @CacheEvict(value = "features", key = "#id"),
            @CacheEvict(value = "features", allEntries = true)
    })
    public FeatureDTO updateFeature(Long id, FeatureDTO featureDTO) {
        Feature existingFeature = featureRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Feature not found with id: " + id));

        // Check for name/version uniqueness if name or version is changed
        if ((!existingFeature.getName().equals(featureDTO.getName()) || !existingFeature.getVersion().equals(featureDTO.getVersion())) &&
                featureRepository.existsByNameAndVersion(featureDTO.getName(), featureDTO.getVersion())) {
            throw new ValidationException(String.format("Feature with name '%s' and version '%d' already exists.",
                    featureDTO.getName(), featureDTO.getVersion()));
        }

        existingFeature.setName(featureDTO.getName());
        existingFeature.setDescription(featureDTO.getDescription());
        existingFeature.setType(featureDTO.getType());
        existingFeature.setVersion(featureDTO.getVersion());
        existingFeature.setSourceDatasetId(featureDTO.getSourceDatasetId());
        existingFeature.setTransformationLogic(featureDTO.getTransformationLogic());
        // createdAt should not be updated

        return convertToDTO(featureRepository.save(existingFeature));
    }

    @Transactional
    @Caching(evict = {
            @CacheEvict(value = "features", key = "#id"),
            @CacheEvict(value = "features", allEntries = true)
    })
    public void deleteFeature(Long id) {
        if (!featureRepository.existsById(id)) {
            throw new ResourceNotFoundException("Feature not found with id: " + id);
        }
        featureRepository.deleteById(id);
    }

    private FeatureDTO convertToDTO(Feature feature) {
        if (feature == null) return null;
        return new FeatureDTO(
                feature.getId(),
                feature.getName(),
                feature.getDescription(),
                feature.getType(),
                feature.getVersion(),
                feature.getSourceDatasetId(),
                feature.getTransformationLogic(),
                feature.getCreatedAt(),
                feature.getLastModifiedAt()
        );
    }

    private Feature convertToEntity(FeatureDTO featureDTO) {
        if (featureDTO == null) return null;
        Feature feature = new Feature();
        feature.setId(featureDTO.getId());
        feature.setName(featureDTO.getName());
        feature.setDescription(featureDTO.getDescription());
        feature.setType(featureDTO.getType());
        feature.setVersion(featureDTO.getVersion());
        feature.setSourceDatasetId(featureDTO.getSourceDatasetId());
        feature.setTransformationLogic(featureDTO.getTransformationLogic());
        feature.setCreatedAt(featureDTO.getCreatedAt()); // Should be set by @PrePersist on new entities
        feature.setLastModifiedAt(featureDTO.getLastModifiedAt()); // Should be set by @PreUpdate on existing
        return feature;
    }
}