package com.ml_utilities_system.service;

import com.ml_utilities_system.dto.ModelDTO;
import com.ml_utilities_system.exception.ResourceNotFoundException;
import com.ml_utilities_system.exception.ValidationException;
import com.ml_utilities_system.model.Dataset;
import com.ml_utilities_system.model.Feature;
import com.ml_utilities_system.model.Model;
import com.ml_utilities_system.repository.DatasetRepository;
import com.ml_utilities_system.repository.FeatureRepository;
import com.ml_utilities_system.repository.ModelRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.cache.annotation.Caching;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

@Service
public class ModelService {

    @Autowired
    private ModelRepository modelRepository;

    @Autowired
    private FeatureRepository featureRepository;

    @Autowired
    private DatasetRepository datasetRepository;

    @Transactional(readOnly = true)
    @Cacheable(value = "models", key = "#id")
    public ModelDTO getModelById(Long id) {
        Model model = modelRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Model not found with id: " + id));
        return convertToDTO(model);
    }

    @Transactional(readOnly = true)
    @Cacheable(value = "models", key = "'all' + #pageable.pageNumber + '_' + #pageable.pageSize")
    public Page<ModelDTO> getAllModels(Pageable pageable) {
        return modelRepository.findAll(pageable).map(this::convertToDTO);
    }

    @Transactional
    @Caching(evict = {
            @CacheEvict(value = "models", allEntries = true)
    })
    public ModelDTO createModel(ModelDTO modelDTO) {
        if (modelRepository.existsByNameAndVersion(modelDTO.getName(), modelDTO.getVersion())) {
            throw new ValidationException(String.format("Model with name '%s' and version '%d' already exists.",
                    modelDTO.getName(), modelDTO.getVersion()));
        }
        Model model = convertToEntity(modelDTO);
        model.setId(null); // Ensure ID is generated by DB
        return convertToDTO(modelRepository.save(model));
    }

    @Transactional
    @Caching(evict = {
            @CacheEvict(value = "models", key = "#id"),
            @CacheEvict(value = "models", allEntries = true)
    })
    public ModelDTO updateModel(Long id, ModelDTO modelDTO) {
        Model existingModel = modelRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Model not found with id: " + id));

        // Check for name/version uniqueness if name or version is changed
        if ((!existingModel.getName().equals(modelDTO.getName()) || !existingModel.getVersion().equals(modelDTO.getVersion())) &&
                modelRepository.existsByNameAndVersion(modelDTO.getName(), modelDTO.getVersion())) {
            throw new ValidationException(String.format("Model with name '%s' and version '%d' already exists.",
                    modelDTO.getName(), modelDTO.getVersion()));
        }

        existingModel.setName(modelDTO.getName());
        existingModel.setDescription(modelDTO.getDescription());
        existingModel.setVersion(modelDTO.getVersion());
        existingModel.setAlgorithm(modelDTO.getAlgorithm());
        existingModel.setModelPath(modelDTO.getModelPath());
        existingModel.setPerformanceMetric(modelDTO.getPerformanceMetric());
        existingModel.setStatus(modelDTO.getStatus());

        if (modelDTO.getFeatureIds() != null && !modelDTO.getFeatureIds().isEmpty()) {
            Set<Feature> features = new HashSet<>(featureRepository.findAllById(modelDTO.getFeatureIds()));
            if (features.size() != modelDTO.getFeatureIds().size()) {
                throw new ValidationException("One or more features not found.");
            }
            existingModel.setFeatures(features);
        } else {
            existingModel.setFeatures(new HashSet<>());
        }

        if (modelDTO.getTrainingDatasetId() != null) {
            Dataset dataset = datasetRepository.findById(modelDTO.getTrainingDatasetId())
                    .orElseThrow(() -> new ResourceNotFoundException("Training dataset not found with id: " + modelDTO.getTrainingDatasetId()));
            existingModel.setTrainingDataset(dataset);
        } else {
            existingModel.setTrainingDataset(null);
        }

        return convertToDTO(modelRepository.save(existingModel));
    }

    @Transactional
    @Caching(evict = {
            @CacheEvict(value = "models", key = "#id"),
            @CacheEvict(value = "models", allEntries = true)
    })
    public void deleteModel(Long id) {
        if (!modelRepository.existsById(id)) {
            throw new ResourceNotFoundException("Model not found with id: " + id);
        }
        modelRepository.deleteById(id);
    }

    private ModelDTO convertToDTO(Model model) {
        if (model == null) return null;
        return new ModelDTO(
                model.getId(),
                model.getName(),
                model.getDescription(),
                model.getVersion(),
                model.getAlgorithm(),
                model.getModelPath(),
                model.getPerformanceMetric(),
                model.getStatus(),
                model.getFeatures().stream().map(Feature::getId).collect(Collectors.toSet()),
                model.getTrainingDataset() != null ? model.getTrainingDataset().getId() : null,
                model.getRegisteredAt(),
                model.getLastModifiedAt()
        );
    }

    private Model convertToEntity(ModelDTO modelDTO) {
        if (modelDTO == null) return null;
        Model model = new Model();
        model.setId(modelDTO.getId());
        model.setName(modelDTO.getName());
        model.setDescription(modelDTO.getDescription());
        model.setVersion(modelDTO.getVersion());
        model.setAlgorithm(modelDTO.getAlgorithm());
        model.setModelPath(modelDTO.getModelPath());
        model.setPerformanceMetric(modelDTO.getPerformanceMetric());
        model.setStatus(modelDTO.getStatus());
        model.setRegisteredAt(modelDTO.getRegisteredAt());
        model.setLastModifiedAt(modelDTO.getLastModifiedAt());

        if (modelDTO.getFeatureIds() != null && !modelDTO.getFeatureIds().isEmpty()) {
            Set<Feature> features = new HashSet<>(featureRepository.findAllById(modelDTO.getFeatureIds()));
            if (features.size() != modelDTO.getFeatureIds().size()) {
                throw new ValidationException("One or more features not found.");
            }
            model.setFeatures(features);
        }

        if (modelDTO.getTrainingDatasetId() != null) {
            Dataset dataset = datasetRepository.findById(modelDTO.getTrainingDatasetId())
                    .orElseThrow(() -> new ResourceNotFoundException("Training dataset not found with id: " + modelDTO.getTrainingDatasetId()));
            model.setTrainingDataset(dataset);
        }
        return model;
    }
}