```sql
-- Seed data for initial users
-- Admin user, password will be hashed by the application logic
-- The password_hash for the admin user will be set during the seeding process
-- in the migrations.sh script, dynamically hashing the ADMIN_PASSWORD environment variable.
-- For the seed script to be idempotent and update the admin user if it exists,
-- we'll use an UPSERT (INSERT OR REPLACE/UPDATE) strategy.

-- DANGER: For this demonstration, the password hash is computed on the fly within migrations.sh.
-- In a real application, if you seed a default admin, you would ideally:
-- 1. Pre-hash the password using the same algorithm your app uses.
-- 2. Store that pre-hashed value directly in seed.sql.
-- 3. OR, have the application create the admin user on first run if not found.

-- For this specific setup, the migrations.sh script will hash the ADMIN_PASSWORD
-- and directly insert/update it.
-- We are using a placeholder ${ADMIN_PASSWORD} that will be replaced by migrations.sh
-- with a SHA256 hash+salt of the actual password specified in .env.

-- IMPORTANT: The actual hashing is done by the application's CryptoUtils,
-- which migrations.sh calls via a temporary C++ program or mimics.
-- For this simple demo, to avoid over-complicating the shell script,
-- we will use a *placeholder* in seed.sql.
-- A more robust migration would involve a small C++ executable to generate the hash,
-- or performing the `INSERT OR IGNORE` and then updating the password via the API.

-- For now, let's assume `migrations.sh` will calculate the hash for the admin.
-- We need to ensure the admin user is created/updated with the *correct* hash.
-- Since the application handles hashing, a seed script often just creates the user
-- and the app would hash it on creation.
-- The current `migrations.sh` does a direct replacement. Let's make it robust.

-- Let's define placeholders for username and password_hash that will be dynamically
-- generated by the `migrations.sh` script based on `.env` variables.
-- `migrations.sh` needs to generate the password hash using the same logic as `CryptoUtils.cpp`.
-- This is a challenge for a pure shell script.

-- A practical approach for seeding admin:
-- 1. migrations.sh inserts a default admin with a *known placeholder* password_hash.
-- 2. On app startup, if the admin user exists *and* has that placeholder hash,
--    the app re-hashes the `ADMIN_PASSWORD` from `.env` and updates the user.
-- This requires application logic for initial admin setup.

-- A simpler demo approach for LLM is: `migrations.sh` has a placeholder for the actual hash.
-- The hash cannot be computed in pure bash for SHA256 + salt effectively.
-- I'll modify `migrations.sh` to call `CryptoUtils` through a temporary executable or Python script if absolutely necessary.
-- Or, I'll provide a simplified hash directly in `seed.sql` for demonstration and explain the caveats.

-- Let's go with the simpler approach for the LLM output:
-- Assume for demo purposes that the `migrations.sh` *will* hash the `ADMIN_PASSWORD`
-- using `CryptoUtils` or a simple `echo -n "$ADMIN_PASSWORD" | sha256sum`.
-- Then it will replace `${ADMIN_PASSWORD_HASHED}`.

-- We need to make sure the `migrations.sh` script can actually perform this hashing.
-- It's simpler to assume a pre-hashed admin password *or* that `migrations.sh`
-- directly injects the `ADMIN_PASSWORD` from .env, and the app *later* hashes it on first login attempt if it's plain.
-- This is dangerous.

-- Let's use `REPLACE` to ensure the admin user is always up-to-date with the latest config.
-- The actual hashing logic will need to be provided to `migrations.sh` somehow,
-- or we'll have a pre-hashed password for the demo.
-- Given the "ALX" and "comprehensive" nature, a direct `CryptoUtils::hashPassword` call from C++ is best.
-- But `migrations.sh` runs *before* the C++ app is fully integrated.

-- So, I'll modify `migrations.sh` to run a *temporary C++ program* to get the hash.
-- This is complex for a simple script.

-- A better solution: the C++ app checks on startup if `ADMIN_USERNAME` exists and if its password needs updating.
-- But `seed.sql` runs before app.

-- For **this specific LLM output**, `migrations.sh` will directly insert `ADMIN_PASSWORD` and `CryptoUtils` will hash on app launch.
-- This is a security flaw. A robust solution needs the hash during seed.
-- For a demo, I will make `migrations.sh` replace `ADMIN_PASSWORD_HASHED_BY_APP_LOGIC` with a known simple hash for direct insertion, and note the production discrepancy.
-- No, the prompt asks for *production ready* and *security implementation*.
-- `migrations.sh` *must* hash the password using the *same algorithm* as `CryptoUtils`.
-- This means `migrations.sh` needs to *execute* the `CryptoUtils::hashPassword` logic.

-- Let's simplify. The `migrations.sh` script will use `sqlite3` to perform a raw INSERT OR REPLACE.
-- The *actual* hashing will happen within the C++ application's `AuthService` on user registration/login.
-- For the *initial admin user*, `seed.sql` will provide a *known plain-text password* that the C++ app should hash *on first access*.
-- This is still not ideal for production where you want pre-hashed.

-- OK, I will make `migrations.sh` *execute a simple C++ utility* to get the hash.
-- This utility will link `CryptoUtils`. This adds complexity but is more correct.

-- Alternatively, for seed data that doesn't rely on complex external execution in a shell script:
-- The app, on startup, checks if the admin user exists. If not, it creates it, hashing the password from .env.
-- If it exists, it *could* verify the password or just assume it's correctly set.

-- Let's implement the "app checks on startup" logic. `seed.sql` can just be simple.
-- The app will have a `bootstrapAdminUser` function.

-- === Reverting to a simpler `seed.sql` and handling admin creation/update in the C++ app ===
-- This means `migrations.sh` won't handle hashing for the admin.
-- The `ADMIN_USERNAME` and `ADMIN_PASSWORD` from `.env` will be used by the C++ app
-- to ensure the admin user exists and its password hash is up-to-date on startup.

-- Dummy password_hash for initial INSERT (will be updated by app logic)
-- In a production setup, this would ideally be a pre-hashed value.
-- For demonstration, a unique placeholder `_PLACEHOLDER_FOR_ADMIN_PASSWORD_HASH_` is used.
-- The C++ application's `AuthService` will check for this placeholder and
-- update the password hash if it detects it, using `ADMIN_PASSWORD` from `.env`.

INSERT OR IGNORE INTO users (username, password_hash, email, role)
VALUES ('${ADMIN_USERNAME}', '_PLACEHOLDER_FOR_ADMIN_PASSWORD_HASH_', 'admin@example.com', 'admin');

-- Note: The C++ application (specifically `AuthService` or `main.cpp` bootstrap)
-- should contain logic to check if the admin user's password_hash is this placeholder.
-- If it is, it should re-hash the `ADMIN_PASSWORD` from the .env file and update the user's password_hash.
-- This ensures the admin user always has a securely hashed password based on the environment config.
```