# Stage 1: Build the Spring Boot application
FROM maven:3.9.5-amazoncorretto-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Create the final Docker image
FROM openjdk:17-jdk-slim
WORKDIR /app
# Copy the built JAR from the build stage
COPY --from=build /app/target/*.jar app.jar
# Expose the port the Spring Boot application runs on
EXPOSE 8080
# Run the application
ENTRYPOINT ["java","-jar","app.jar"]