#pragma once

#include <string>
#include <chrono>
#include <nlohmann/json.hpp>

struct User {
    std::string id;
    std::string username;
    std::string email;
    std::string password_hash; // Store hashed password
    std::chrono::system_clock::time_point created_at;
    std::chrono::system_clock::time_point updated_at;

    // Default constructor
    User() = default;

    // Constructor for creating new users (ID and timestamps will be generated by DB)
    User(const std::string& username, const std::string& email, const std::string& password_hash)
        : username(username), email(email), password_hash(password_hash) {}

    // Constructor for retrieving from DB
    User(const std::string& id, const std::string& username, const std::string& email,
         const std::string& password_hash, std::chrono::system_clock::time_point created_at,
         std::chrono::system_clock::time_point updated_at)
        : id(id), username(username), email(email), password_hash(password_hash),
          created_at(created_at), updated_at(updated_at) {}
};

// JSON serialization for User
void to_json(nlohmann::json& j, const User& u);
// JSON deserialization for User (for registration/update requests)
void from_json(const nlohmann::json& j, User& u);
```