```typescript
// This script is run *before* `tsc` to generate a `data-source.js`
// for the compiled output, ensuring TypeORM CLI works with `.js` files.
// It's a workaround for TypeORM CLI not directly supporting TS paths in `dist`.

import fs from 'fs';
import path from 'path';

const configTemplate = `
// This file is auto-generated by generate-typeorm-config.ts for TypeORM CLI usage with compiled JS.
// Do not edit this file directly.
import { DataSource } from 'typeorm';
import { env } from '../../config/env.config';
import { User } from '../entities/User';
import { Project } from '../entities/Project';
import { Task } from '../entities/Task';

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: env.DB_HOST,
  port: env.DB_PORT,
  username: env.DB_USERNAME,
  password: env.DB_PASSWORD,
  database: env.DB_DATABASE,
  synchronize: false,
  logging: env.NODE_ENV === 'development',
  entities: [User, Project, Task],
  migrations: [__dirname + '/../migrations/*.js'], // For compiled JS migrations
  subscribers: [],
});
`;

const outputPath = path.resolve(__dirname, '../../dist/database/config/data-source.js');

// Ensure the directory exists
fs.mkdirSync(path.dirname(outputPath), { recursive: true });

// Write the compiled-friendly data-source.js
fs.writeFileSync(outputPath, configTemplate.replace(/\.ts/g, '.js'));

console.log('Generated dist/database/config/data-source.js for TypeORM CLI.');
```