```java
package com.alx.pm.service;

import com.alx.pm.dto.CategoryDTO;
import com.alx.pm.entity.Category;
import com.alx.pm.exception.ApiException;
import com.alx.pm.exception.ResourceNotFoundException;
import com.alx.pm.repository.CategoryRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class CategoryService {

    private final CategoryRepository categoryRepository;

    @Cacheable("categories")
    @Transactional(readOnly = true)
    public List<CategoryDTO> getAllCategories() {
        log.info("Fetching all categories from database");
        return categoryRepository.findAll().stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }

    @Cacheable(value = "categories", key = "#id")
    @Transactional(readOnly = true)
    public CategoryDTO getCategoryById(Long id) {
        log.info("Fetching category with ID: {}", id);
        Category category = categoryRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Category", "id", id));
        return convertToDto(category);
    }

    @CacheEvict(value = "categories", allEntries = true) // Evict all categories cache on creation
    @Transactional
    public CategoryDTO createCategory(CategoryDTO categoryDTO) {
        if (categoryRepository.existsByName(categoryDTO.getName())) {
            throw new ApiException(HttpStatus.CONFLICT, "Category with name '" + categoryDTO.getName() + "' already exists.");
        }
        Category category = convertToEntity(categoryDTO);
        category.setId(null); // Ensure ID is generated by DB
        Category savedCategory = categoryRepository.save(category);
        log.info("Created new category: {}", savedCategory.getName());
        return convertToDto(savedCategory);
    }

    @CacheEvict(value = "categories", allEntries = true) // Evict all categories cache on update
    @Transactional
    public CategoryDTO updateCategory(Long id, CategoryDTO categoryDTO) {
        Category existingCategory = categoryRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Category", "id", id));

        if (categoryRepository.existsByName(categoryDTO.getName()) &&
            !existingCategory.getName().equals(categoryDTO.getName())) {
            throw new ApiException(HttpStatus.CONFLICT, "Category with name '" + categoryDTO.getName() + "' already exists.");
        }

        existingCategory.setName(categoryDTO.getName());
        Category updatedCategory = categoryRepository.save(existingCategory);
        log.info("Updated category with ID {}: {}", id, updatedCategory.getName());
        return convertToDto(updatedCategory);
    }

    @CacheEvict(value = "categories", allEntries = true) // Evict all categories cache on delete
    @Transactional
    public void deleteCategory(Long id) {
        if (!categoryRepository.existsById(id)) {
            throw new ResourceNotFoundException("Category", "id", id);
        }
        categoryRepository.deleteById(id);
        log.info("Deleted category with ID: {}", id);
    }

    private CategoryDTO convertToDto(Category category) {
        return new CategoryDTO(category.getId(), category.getName());
    }

    private Category convertToEntity(CategoryDTO categoryDTO) {
        Category category = new Category();
        category.setId(categoryDTO.getId());
        category.setName(categoryDTO.getName());
        return category;
    }
}
```