```java
package com.alx.pm.service;

import com.alx.pm.dto.ProductDTO;
import com.alx.pm.entity.Category;
import com.alx.pm.entity.Product;
import com.alx.pm.exception.ResourceNotFoundException;
import com.alx.pm.repository.CategoryRepository;
import com.alx.pm.repository.ProductRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class ProductService {

    private final ProductRepository productRepository;
    private final CategoryRepository categoryRepository;

    @Cacheable("products")
    @Transactional(readOnly = true)
    public Page<ProductDTO> getAllProducts(Pageable pageable, String name, Long categoryId, Double minPrice, Double maxPrice) {
        log.info("Fetching products with pageable: {}, name: {}, categoryId: {}, minPrice: {}, maxPrice: {}",
                pageable, name, categoryId, minPrice, maxPrice);
        Page<Product> products = productRepository.findByCriteria(name, categoryId, minPrice, maxPrice, pageable);
        return products.map(this::convertToDto);
    }

    @Cacheable(value = "products", key = "#id")
    @Transactional(readOnly = true)
    public ProductDTO getProductById(Long id) {
        log.info("Fetching product with ID: {}", id);
        Product product = productRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Product", "id", id));
        return convertToDto(product);
    }

    @CacheEvict(value = "products", allEntries = true) // Evict all products cache on creation
    @Transactional
    public ProductDTO createProduct(ProductDTO productDTO) {
        Category category = categoryRepository.findById(productDTO.getCategoryId())
                .orElseThrow(() -> new ResourceNotFoundException("Category", "id", productDTO.getCategoryId()));

        Product product = convertToEntity(productDTO, category);
        product.setId(null); // Ensure ID is generated by DB
        Product savedProduct = productRepository.save(product);
        log.info("Created new product: {}", savedProduct.getName());
        return convertToDto(savedProduct);
    }

    @CacheEvict(value = "products", allEntries = true) // Evict all products cache on update
    @Transactional
    public ProductDTO updateProduct(Long id, ProductDTO productDTO) {
        Product existingProduct = productRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Product", "id", id));

        Category category = categoryRepository.findById(productDTO.getCategoryId())
                .orElseThrow(() -> new ResourceNotFoundException("Category", "id", productDTO.getCategoryId()));

        existingProduct.setName(productDTO.getName());
        existingProduct.setDescription(productDTO.getDescription());
        existingProduct.setPrice(productDTO.getPrice());
        existingProduct.setStock(productDTO.getStock());
        existingProduct.setCategory(category);

        Product updatedProduct = productRepository.save(existingProduct);
        log.info("Updated product with ID {}: {}", id, updatedProduct.getName());
        return convertToDto(updatedProduct);
    }

    @CacheEvict(value = "products", allEntries = true) // Evict all products cache on delete
    @Transactional
    public void deleteProduct(Long id) {
        if (!productRepository.existsById(id)) {
            throw new ResourceNotFoundException("Product", "id", id);
        }
        productRepository.deleteById(id);
        log.info("Deleted product with ID: {}", id);
    }

    private ProductDTO convertToDto(Product product) {
        ProductDTO dto = new ProductDTO();
        dto.setId(product.getId());
        dto.setName(product.getName());
        dto.setDescription(product.getDescription());
        dto.setPrice(product.getPrice());
        dto.setStock(product.getStock());
        dto.setCategoryId(product.getCategory().getId());
        dto.setCategoryName(product.getCategory().getName());
        dto.setCreatedAt(product.getCreatedAt());
        dto.setUpdatedAt(product.getUpdatedAt());
        return dto;
    }

    private Product convertToEntity(ProductDTO productDTO, Category category) {
        Product product = new Product();
        product.setName(productDTO.getName());
        product.setDescription(productDTO.getDescription());
        product.setPrice(productDTO.getPrice());
        product.setStock(productDTO.getStock());
        product.setCategory(category);
        return product;
    }
}
```