```python
import time
from locust import HttpUser, task, between

class CMSUser(HttpUser):
    wait_time = between(1, 2.5) # Users will wait between 1 and 2.5 seconds between tasks

    # Assume we have an admin user for getting tokens for privileged actions
    # In a real scenario, you'd register/login a user to get these dynamically
    # For simplicity, we hardcode, but recommended is dynamic login.
    admin_access_token = "" # Placeholder: Get this from a /login call
    editor_access_token = "" # Placeholder
    regular_user_access_token = "" # Placeholder

    # Store some IDs for common operations
    post_ids = []
    category_ids = []
    user_ids = []
    
    def on_start(self):
        """ on_start is called when a Locust user starts running """
        # Perform initial login to get tokens
        # Example:
        # login_data = {"username": "admin_test", "password": "password"}
        # response = self.client.post("/api/auth/login", json=login_data)
        # if response.status_code == 200:
        #     self.admin_access_token = response.json().get("access_token")
        # else:
        #     print("Admin login failed. Cannot perform privileged tasks.")
        
        # Populate IDs for tasks
        self._get_initial_data()

    def _get_initial_data(self):
        # Fetch some posts
        response = self.client.get("/api/posts?status=published")
        if response.status_code == 200:
            self.post_ids = [p['id'] for p in response.json() if 'id' in p]

        # Fetch some categories
        response = self.client.get("/api/categories")
        if response.status_code == 200:
            self.category_ids = [c['id'] for c in response.json() if 'id' in c]
        
        # Fetch some users (requires admin token)
        # if self.admin_access_token:
        #     response = self.client.get("/api/users", headers={"Authorization": f"Bearer {self.admin_access_token}"})
        #     if response.status_code == 200:
        #         self.user_ids = [u['id'] for u in response.json() if 'id' in u]
        # else:
        #    print("Skipping fetching user IDs as admin token is not available.")


    @task(10) # 10 times more likely to run than a task with weight 1
    def view_homepage(self):
        self.client.get("/")

    @task(5)
    def view_all_published_posts(self):
        self.client.get("/api/posts?status=published")

    @task(3)
    def view_single_post(self):
        if self.post_ids:
            post_id = self.post_ids[0] # Just pick one for simplicity
            self.client.get(f"/api/posts/{post_id}")

    @task(2)
    def view_all_categories(self):
        self.client.get("/api/categories")

    # Example of a POST request (requires authentication)
    # This would typically be done by an editor/admin
    # @task(1)
    # def create_new_post(self):
    #     if self.editor_access_token and self.category_ids:
    #         post_data = {
    #             "title": f"Load Test Post {time.time()}",
    #             "slug": f"load-test-post-{time.time()}",
    #             "content": "This is a post generated by a load test.",
    #             "category_id": self.category_ids[0],
    #             "status": "draft"
    #         }
    #         self.client.post("/api/posts", json=post_data, headers={
    #             "Authorization": f"Bearer {self.editor_access_token}"
    #         })
    #     else:
    #         print("Skipping post creation: editor token or category not available.")

    # Example of a PUT request (requires authentication and specific post ownership/admin)
    # @task(0.5)
    # def update_post_status(self):
    #     if self.admin_access_token and self.post_ids:
    #         post_id = self.post_ids[0]
    #         update_data = {"status": "published"}
    #         self.client.put(f"/api/posts/{post_id}", json=update_data, headers={
    #             "Authorization": f"Bearer {self.admin_access_token}"
    #         })
    #     else:
    #         print("Skipping post update: admin token or post not available.")
```