```javascript
const httpStatus = require('http-status');
const jwt = require('jsonwebtoken');
const config = require('../config/config');
const { User } = require('../models');
const ApiError = require('../utils/ApiError');
const catchAsync = require('../utils/catchAsync');
const logger = require('../config/logger');

/**
 * Express middleware for authenticating JWT tokens.
 * Attaches the user object to the request if authentication is successful.
 */
const auth = (...requiredRoles) => catchAsync(async (req, res, next) => {
  let token;
  if (req.headers.authorization && req.headers.authorization.startsWith('Bearer')) {
    token = req.headers.authorization.split(' ')[1];
  }

  if (!token) {
    logger.warn('Authentication failed: No token provided');
    return next(new ApiError(httpStatus.UNAUTHORIZED, 'Please authenticate'));
  }

  try {
    const payload = jwt.verify(token, config.jwt.secret);

    // If it's a refresh token, we expect the route to handle it explicitly (e.g., refresh token endpoint)
    // For general auth, we expect an access token.
    if (payload.type && payload.type !== 'access') {
      logger.warn(`Authentication failed: Invalid token type for access. Type: ${payload.type}`);
      throw new Error('Invalid token type');
    }

    const user = await User.findByPk(payload.sub);

    if (!user) {
      logger.warn(`Authentication failed: User with ID ${payload.sub} not found.`);
      return next(new ApiError(httpStatus.UNAUTHORIZED, 'User not found'));
    }

    req.user = user; // Attach user object to the request

    // Check user roles if specified
    if (requiredRoles.length > 0) {
      const hasRequiredRole = requiredRoles.includes(user.role);
      if (!hasRequiredRole) {
        logger.warn(`Authorization failed: User ${user.email} (${user.role}) does not have required roles: ${requiredRoles.join(', ')}`);
        return next(new ApiError(httpStatus.FORBIDDEN, 'Forbidden: Insufficient permissions'));
      }
    }

    next();
  } catch (error) {
    logger.error(`JWT authentication error: ${error.message}`, error);
    if (error instanceof jwt.TokenExpiredError) {
      return next(new ApiError(httpStatus.UNAUTHORIZED, 'Token expired'));
    }
    if (error instanceof jwt.JsonWebTokenError) {
      return next(new ApiError(httpStatus.UNAUTHORIZED, 'Invalid token'));
    }
    next(new ApiError(httpStatus.UNAUTHORIZED, 'Authentication failed'));
  }
});

// Middleware for handling refresh tokens specifically
const refreshAuth = catchAsync(async (req, res, next) => {
  let token;
  if (req.body.refreshToken) {
    token = req.body.refreshToken;
  } else if (req.headers.authorization && req.headers.authorization.startsWith('Bearer')) {
    // Also allow refresh token in header for consistency, though body is common
    token = req.headers.authorization.split(' ')[1];
  }

  if (!token) {
    logger.warn('Refresh token authentication failed: No token provided');
    return next(new ApiError(httpStatus.UNAUTHORIZED, 'Refresh token required'));
  }

  try {
    const payload = jwt.verify(token, config.jwt.secret);

    if (payload.type !== 'refresh') {
      logger.warn(`Refresh token authentication failed: Invalid token type for refresh. Type: ${payload.type}`);
      throw new Error('Invalid token type for refresh');
    }

    const user = await User.findByPk(payload.sub);
    if (!user) {
      logger.warn(`Refresh token authentication failed: User with ID ${payload.sub} not found.`);
      return next(new ApiError(httpStatus.UNAUTHORIZED, 'Invalid refresh token - user not found'));
    }

    // In a real app, you would also check if this specific refresh token is valid in your DB/Redis.
    // For simplicity, we are assuming any valid refresh token generated by our system is fine.
    req.user = user;
    next();
  } catch (error) {
    logger.error(`Refresh token validation error: ${error.message}`, error);
    if (error instanceof jwt.TokenExpiredError) {
      return next(new ApiError(httpStatus.UNAUTHORIZED, 'Refresh token expired. Please log in again.'));
    }
    if (error instanceof jwt.JsonWebTokenError) {
      return next(new ApiError(httpStatus.UNAUTHORIZED, 'Invalid refresh token.'));
    }
    next(new ApiError(httpStatus.UNAUTHORIZED, 'Refresh token validation failed.'));
  }
});

module.exports = { auth, refreshAuth };
```