from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required, get_jwt_identity
from app.database import db
from app.models import Report, MonitoredDatabase, ReportType
from app.utils.errors import APIError
from app.extensions import cache, limiter
from datetime import datetime

report_api_bp = Blueprint('report_api', __name__)

@report_api_bp.route('/', methods=['GET'])
@jwt_required()
@cache.cached(timeout=60, query_string=True) # Cache for 60 seconds
@limiter.limit("60 per hour")
def get_all_reports():
    """
    List all reports generated for the current user's monitored databases.
    Requires: valid JWT.
    Query params: `db_id` (optional, filter by database), `report_type` (optional, filter by type).
    Returns: List of reports.
    """
    user_id = get_jwt_identity()
    db_id_filter = request.args.get('db_id')
    report_type_filter = request.args.get('report_type')

    query = Report.query.filter_by(user_id=user_id)

    if db_id_filter:
        try:
            # Ensure the user owns this database
            MonitoredDatabase.query.filter_by(id=db_id_filter, user_id=user_id).first_or_404()
            query = query.filter_by(db_id=db_id_filter)
        except Exception:
            raise APIError("Monitored database not found or access denied", status_code=404)

    if report_type_filter:
        try:
            report_type_enum = ReportType[report_type_filter.upper()]
            query = query.filter_by(report_type=report_type_enum)
        except KeyError:
            raise APIError(f"Invalid report type: {report_type_filter}. Allowed: {', '.join([rt.value for rt in ReportType])}", status_code=400)

    reports = query.order_by(Report.generated_at.desc()).all()
    return jsonify([report.to_dict() for report in reports]), 200

@report_api_bp.route('/<int:report_id>', methods=['GET'])
@jwt_required()
@cache.cached(timeout=30) # Cache for 30 seconds
@limiter.limit("100 per hour")
def get_report_details(report_id):
    """
    Get details of a specific report.
    Requires: valid JWT, report_id.
    Returns: Report details.
    """
    user_id = get_jwt_identity()
    report = Report.query.filter_by(id=report_id, user_id=user_id).first()
    if not report:
        raise APIError("Report not found", status_code=404)
    return jsonify(report.to_dict()), 200

# Reports are typically generated by tasks, not directly via API POST,
# but we might have a conceptual "generate ad-hoc report" endpoint if desired.
# For this comprehensive system, report generation is part of the analysis tasks.
```