```cpp
#ifndef USER_H
#define USER_H

#include <string>
#include <optional>
#include <nlohmann/json.hpp>

namespace PaymentProcessor {
namespace Models {

enum class UserRole {
    ADMIN,
    MERCHANT,
    VIEWER
};

// Helper for JSON serialization of UserRole
NLOHMANN_JSON_SERIALIZE_ENUM(UserRole, {
    {UserRole::ADMIN, "ADMIN"},
    {UserRole::MERCHANT, "MERCHANT"},
    {UserRole::VIEWER, "VIEWER"}
})

struct User {
    std::optional<long long> id; // optional for new users (before ID is assigned)
    std::string username;
    std::string passwordHash; // Stored hash, never plain password
    std::string email;
    UserRole role;
    std::string createdAt; // ISO 8601 string
    std::string updatedAt; // ISO 8601 string

    // Default constructor
    User() : role(UserRole::MERCHANT) {}

    // Constructor for creating a new user (ID will be generated by DB)
    User(std::string username, std::string passwordHash, std::string email, UserRole role)
        : username(std::move(username)), passwordHash(std::move(passwordHash)), email(std::move(email)), role(role) {}

    // Constructor for loading from DB
    User(long long id, std::string username, std::string passwordHash, std::string email, UserRole role, std::string createdAt, std::string updatedAt)
        : id(id), username(std::move(username)), passwordHash(std::move(passwordHash)), email(std::move(email)), role(role), createdAt(std::move(createdAt)), updatedAt(std::move(updatedAt)) {}

    // Convert User object to JSON
    nlohmann::json toJson() const {
        nlohmann::json j;
        if (id) j["id"] = *id;
        j["username"] = username;
        // DO NOT INCLUDE passwordHash IN API RESPONSES
        j["email"] = email;
        j["role"] = role;
        j["createdAt"] = createdAt;
        j["updatedAt"] = updatedAt;
        return j;
    }
};

} // namespace Models
} // namespace PaymentProcessor

#endif // USER_H
```