```python
"""Initial migration

Revision ID: YOUR_REVISION_ID
Revises: 
Create Date: 2023-10-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'YOUR_REVISION_ID'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('target_databases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('db_type', sa.String(length=50), nullable=False),
    sa.Column('connection_string', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('target_db_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('analyzed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['target_db_id'], ['target_databases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('target_db_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('suggestion_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sql_statement', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('suggested_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['performance_metrics.id'], ),
    sa.ForeignKeyConstraint(['suggested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_db_id'], ['target_databases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization_suggestions')
    op.drop_table('performance_metrics')
    op.drop_table('target_databases')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
```