-- Seed Data for E-commerce Application

-- NOTE: Passwords here are plaintext for demonstration.
-- In a real seed script, you would pre-hash them using the same BcryptWrapper
-- used by the application, or a similar utility.

-- Users
INSERT INTO users (id, username, email, password_hash, role, first_name, last_name, phone_number, address, created_at, updated_at) VALUES
('usr_1', 'adminuser', 'admin@example.com', '$2a$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'admin', 'Admin', 'User', '111-222-3333', '123 Admin St, City, Country', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('usr_2', 'john_doe', 'john.doe@example.com', '$2a$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'customer', 'John', 'Doe', '444-555-6666', '456 Customer Ave, Town, Country', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('usr_3', 'jane_smith', 'jane.smith@example.com', '$2a$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'customer', 'Jane', 'Smith', '777-888-9999', '789 Buyer Rd, Village, Country', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Products
INSERT INTO products (id, name, description, price, stock_quantity, category, image_url, created_at, updated_at) VALUES
('prod_1', 'Laptop Pro X', 'Powerful laptop for professionals.', 1200.00, 50, 'Electronics', 'http://example.com/images/laptop.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('prod_2', 'Wireless Mouse', 'Ergonomic wireless mouse.', 25.50, 200, 'Accessories', 'http://example.com/images/mouse.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('prod_3', 'Mechanical Keyboard', 'RGB Mechanical Keyboard with Cherry MX switches.', 110.00, 75, 'Accessories', 'http://example.com/images/keyboard.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('prod_4', 'Smart Watch 3', 'Advanced smart watch with health tracking.', 199.99, 120, 'Wearables', 'http://example.com/images/smartwatch.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Cart Items (Example: John Doe's cart)
INSERT INTO cart_items (id, user_id, product_id, quantity, created_at, updated_at) VALUES
('cart_1', 'usr_2', 'prod_1', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('cart_2', 'usr_2', 'prod_3', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Orders (Example: Jane Smith's order)
INSERT INTO orders (id, user_id, order_date, total_amount, status, shipping_address, payment_method, created_at, updated_at) VALUES
('ord_1', 'usr_3', CURRENT_TIMESTAMP, 1310.00, 'processing', '789 Buyer Rd, Village, Country', 'Credit Card', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Order Items for ord_1
INSERT INTO order_items (id, order_id, product_id, quantity, price, created_at, updated_at) VALUES
('orditem_1', 'ord_1', 'prod_1', 1, 1200.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('orditem_2', 'ord_1', 'prod_3', 1, 110.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- IMPORTANT: The '$2a$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' placeholders for password_hash MUST be replaced
-- with actual bcrypt hashes generated by `BcryptWrapper::hashPassword("your_password")`.
-- For example, for 'adminuser' with password 'Admin@123', you would replace it with the hash generated.
--
-- To generate hashes:
-- 1. Compile `BcryptWrapper.cpp` with `main.cpp` using a temporary test executable.
-- 2. Run it to print hashes for desired passwords.
--    e.g., `std::cout << BcryptWrapper::hashPassword("Admin@123") << std::endl;`
-- 3. Copy the output into this file.