```python
"""Initial database schema

Revision ID: <generated_id>
Revises: 
Create Date: 2023-10-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # for UUID type
import uuid # for default UUID generation in op.create_table


# revision identifiers, used by Alembic.
revision = '<generated_id>'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='Primary key, unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('items',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='Primary key, unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=True)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_table('orders',
    sa.Column('customer_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('shipping_address', sa.String(length=500), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='Primary key, unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=True)
    op.create_table('order_items',
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.Float(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='Primary key, unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'item_id', 'id') # Note: id is also a PK, but composite is order_id, item_id
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
```